apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-website
  template:
    metadata:
      labels:
        app: ecommerce-website
    spec:
      containers:
      - name: ecommerce-website
        image: cloudikeme/ecom-web:v0.1 
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "500m" 
            memory: "512Mi" 
          limits:
            cpu: "1"
            memory: "1Gi" 
        env:
        - name: DB_HOST
          value: mysql-service 
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets 
              key: ecomuser
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets 
              key: ecompassword
        - name: DB_NAME
          value: ecomdb